apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: <<NAMESPACE>>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <<APP NAME>>
  template:
    metadata:
      labels:
        app: <<NAME>>
    spec:
      containers:
      - name: <<APP NAME>>
        image: <<IMAGE PATH>>
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 2
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi